### PR TITLE
integration of german translation in layouts

### PR DESCRIPTION
**Pull request by hoodie**
This change is [Reviewable](https://reviewable.io/reviews/rust-lang-de/rust-www/6)

### CODE REVIEW

**Comment by panicbit** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[_layouts/de-DE/basic.html, line 9 at r1](https://reviewable.io:443/reviews/rust-lang-de/rust-www/6#-KUE8tLQq26x8LC11Ry1:-KUE8tLQq26x8LC11Ry2:b-1pmnrh) ([raw file](https://github.com/rust-lang-de/rust-www/blob/0db4143c8bea1546f739c41cf3ad673f83493522/_layouts/de-DE/basic.html#L9)):*
> ```HTML
>     <meta name="viewport" content="width=device-width, initial-scale=1">
>     <title>{{ page.title }}</title>
>     <meta name="keywords" content="Rust, Rust programming language, rustlang, rust-lang, Mozilla Rust">
> ```

Die Metadaten sollten am Besten auch noch übersetzt werden.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/rust-lang-de/rust-www/6)*

**Comment by hoodie** [comment]
Danke

**Comment by hoodie** [comment]
check :D

**Comment by panicbit** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/rust-lang-de/rust-www/6)*

**Pull request merged**
