### PR TITLE
german translation of: community.md

### PR DESCRIPTION
**Pull request by hoodie**
This change is [Reviewable](https://reviewable.io/reviews/rust-lang-de/rust-www/4)

### CODE REVIEW

**Comment by panicbit** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[de-DE/community.md, line 34 at r1](https://reviewable.io:443/reviews/rust-lang-de/rust-www/4#-KUDv5rvtIgIo_TXXgCH:-KUDv5rvtIgIo_TXXgCI:biqg95w) ([raw file](https://github.com/rust-lang-de/rust-www/blob/851e333a408cd04e306dda2e0473513d876428c1/de-DE/community.md#L34)):*
> ```Markdown
> - [#rust-beginners][beginners_irc], an IRC channel that
>   loves answering questions at any depth.
> - The [Users Forum][users_forum], for discussion of all
> ```

Ich würde die Verweise zu den Englischen Ressourcen vielleicht beibehalten.

---

*[de-DE/community.md, line 38 at r1](https://reviewable.io:443/reviews/rust-lang-de/rust-www/4#-KUDu3VlRFrDHXiAyb3X:-KUDu3Vm07EL78msntFm:bejnncq) ([raw file](https://github.com/rust-lang-de/rust-www/blob/7b5038e58c440011001335f5122ccd979280d8fe/de-DE/community.md#L38)):*
> ```Markdown
> 
> ### Deutsch
> - [#rust-de][de_irc], der offizielle deutsche IRC Channel.
> ```

Können wir uns denn als offiziell bezeichnen? :smile: 

---

*[de-DE/community.md, line 107 at r1](https://reviewable.io:443/reviews/rust-lang-de/rust-www/4#-KUDwkuWMBi1JIoSmQCJ:-KUDwkuWMBi1JIoSmQCK:b-t8se34) ([raw file](https://github.com/rust-lang-de/rust-www/blob/7b5038e58c440011001335f5122ccd979280d8fe/de-DE/community.md#L107)):*
> ```Markdown
> 
> [IRC]: https://de.wikipedia.org/wiki/Internet_Relay_Chat
> [beginners_irc]: https://client00.chat.mibbit.com/?server=irc.mozilla.org&channel=%23rust-beginners
> ```

Es wäre gut, wenn das `client00.` entfernt wird.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/rust-lang-de/rust-www/4)*

**Comment by panicbit** [comment]
Reviewed 1 of 1 files at r1.
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/rust-lang-de/rust-www/4)*

**Comment by panicbit** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/rust-lang-de/rust-www/4)*

**Comment by hoodie** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[de-DE/community.md, line 34 at r1](https://reviewable.io:443/reviews/rust-lang-de/rust-www/4#-KUDv5rvtIgIo_TXXgCH:-KUDywG7M4YSXq8k6j-n:b47rs1y) ([raw file](https://github.com/rust-lang-de/rust-www/blob/851e333a408cd04e306dda2e0473513d876428c1/de-DE/community.md#L34)):*
<details><summary><i>Previously, panicbit wrote…</i></summary>
> Ich würde die Verweise zu den Englischen Ressourcen vielleicht beibehalten.
</details>
sind doch da, direkt oben drüber !?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/rust-lang-de/rust-www/4)*

**Comment by hoodie** [comment]
*[de-DE/community.md, line 38 at r1](https://reviewable.io:443/reviews/rust-lang-de/rust-www/4#-KUDu3VlRFrDHXiAyb3X:-KUDzX94wjbT--mcAmO2:b-fgyyav) ([raw file](https://github.com/rust-lang-de/rust-www/blob/7b5038e58c440011001335f5122ccd979280d8fe/de-DE/community.md#L38)):*
<details><summary><i>Previously, panicbit wrote…</i></summary>
> Können wir uns denn als offiziell bezeichnen? :smile: 
</details>
ach komm :D 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/rust-lang-de/rust-www/4)*

**Comment by hoodie** [comment]
check

**Comment by panicbit** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[de-DE/community.md, line 34 at r1](https://reviewable.io:443/reviews/rust-lang-de/rust-www/4#-KUDv5rvtIgIo_TXXgCH:-KUDzah6UnpdblllzLUA:b-phnpes) ([raw file](https://github.com/rust-lang-de/rust-www/blob/851e333a408cd04e306dda2e0473513d876428c1/de-DE/community.md#L34)):*
<details><summary><i>Previously, hoodie (Hendrik Sollich) wrote…</i></summary>
> sind doch da, direkt oben drüber !?
</details>
My bad :+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/rust-lang-de/rust-www/4)*

**Comment by panicbit** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/rust-lang-de/rust-www/4)*

**Pull request merged**
