### PR TITLE
translated: downloads

### PR DESCRIPTION
**Pull request by hoodie**
This change is [Reviewable](https://reviewable.io/reviews/rust-lang-de/rust-www/3)

### CODE REVIEW

**Comment by panicbit** [comment]
Reviewed 19 of 20 files at r1.
Review status: 19 of 20 files reviewed at latest revision, 2 unresolved discussions.

---

*[de-DE/downloads.html, line 14 at r1](https://reviewable.io:443/reviews/rust-lang-de/rust-www/3#-KUDpxOtODzB9PwbApEl:-KUDpxOtODzB9PwbApEm:bk84hto) ([raw file](https://github.com/rust-lang-de/rust-www/blob/32f0ccbb65a247908631ed0371a090d7a3e623cc/de-DE/downloads.html#L14)):*
> ```HTML
>         <h3>{{ site.stable_date | date: "%d.%m.%Y" }}</h3>
>         <p>
> 	  Der
> ```

`Der` → `Die`

---

*[de-DE/downloads.html, line 113 at r1](https://reviewable.io:443/reviews/rust-lang-de/rust-www/3#-KUDpEueE5kCzh1ZbP83:-KUDpEueE5kCzh1ZbP84:bk84hto) ([raw file](https://github.com/rust-lang-de/rust-www/blob/32f0ccbb65a247908631ed0371a090d7a3e623cc/de-DE/downloads.html#L113)):*
> ```HTML
>         <h2 id="nightly">Nightly&nbsp; ({{ site.nightly }})</h2>
>         <p>
>         Der aktuelle Entwicklungsversion.
> ```

`Der` → `Die`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/rust-lang-de/rust-www/3)*

**Comment by panicbit** [comment]
Reviewed 1 of 20 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/rust-lang-de/rust-www/3)*

**Comment by hoodie** [comment]
check

**Comment by panicbit** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/rust-lang-de/rust-www/3)*

**Pull request merged**
